=== giullianabeatriz/pos-2025-tarefas/xsd/cardapio.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:c="http://cardapio.org"
        targetNamespace="http://cardapioespecial.org"
        elementFormDefault="qualified">
        
<element name="cardapio">
    <complexType>
      <sequence>
        <element name="prato" minOccurs="1" maxOccurs="unbounded">
            <complexType>
                <sequence>
                    <element name="nome" type="string"/>
                    <element name="descrição" type="string"/>
                    <element name="ingredientes"/>
                    <complexType>
                        <sequence>
                            <element name="ingrediente" type="string" minOccurs="1" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>
                <element name="preco">
                    <simpleType>
                        <restriction base="decimal">
                            <fractionDigits value="2"/>
                        </restriction>
                    </simpleType>
                </element>
                <element name="calorias" type="integer"/>
                <element name="tempoPreparo" type="string"/>
                <attribute name="id" type="integer" use="required"/>
            </complexType>
        </element>
    </complexType>
</element>
</schema>

=== giullianabeatriz/pos-2025-tarefas/xsd/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<cardapio xmlns="http://cardapioespecial.org" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://cardapioespecial.org cardapio.xsd">

<prato id="P01">
            <nome>Macarronada de frango</nome>
        <descricao>Esse prato é considerado um dos melhores do nosso cardápio.</descricao>
        <ingredientes>
            macarrão; 
            molho branco;
            frango.
        </ingredientes>
        <preco>25.00</preco>
        <calorias>438</calorias>
        <tempoPreparo>20min</tempoPreparo>
    </prato>

    <prato id="P02">
            <nome>Lasanha de frango</nome>
        <descricao>Esse prato é o mais pedido do nosso cardápio.</descricao>
        <ingredientes>
            macarrão; 
            molho;
            queijo;
            presunto;
            frango.
        </ingredientes>
        <preco>30.00</preco>
        <calorias>580</calorias>
        <tempoPreparo>45min</tempoPreparo>
    </prato>

    <prato id="P03">
            <nome>Escondidinho de carne</nome>
        <descricao>Esse prato é o mais simples do nosso cardápio.</descricao>
        <ingredientes>
            batatinha; 
            queijo;
            carne;
            batata palha.
        </ingredientes>
        <preco>35.00</preco>
        <calorias>450</calorias>
        <tempoPreparo>40min</tempoPreparo>
    </prato>

    <prato id="P04">
            <nome>Feijoada</nome>
        <descricao>Esse prato é o mais comum do nosso cardápio.</descricao>
        <ingredientes>
            feijao; 
            calabresa;
            legumes;
            carne.
        </ingredientes>
        <preco>20.00</preco>
        <calorias>400</calorias>
        <tempoPreparo>40min</tempoPreparo>
    </prato>

    <prato id="P05">
            <nome>Sopa de carne</nome>
        <descricao>Esse prato é o mais saboroso do nosso cardápio.</descricao>
        <ingredientes>
            macarrão; 
            batata;
            carne;
            temperos.
        </ingredientes>
        <preco>25.00</preco>
        <calorias>386</calorias>
        <tempoPreparo>50min</tempoPreparo>
    </prato>
</cardapio>
